name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkitgtk-6.0-dev
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Download platform binary
        run: |
          python -c "import os, sys; sys.path.append(os.path.join(os.getcwd(), 'src')); from webview._webview_ffi import _be_sure_libraries; _be_sure_libraries()"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: "cp312-*"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_SKIP: "*-musllinux*"
          #CIBW_BEFORE_BUILD_LINUX: "yum install -y webkit2gtk3-devel"
          #CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: dist-${{ matrix.os }}
          path: wheelhouse/*.whl

  publish:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: List to easy debug
        run: find dist

      - name: Prepare distribution
        run: |
          mkdir final_dist
          cp dist/*/*.whl final_dist/

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install --upgrade twine
          twine upload final_dist/*.whl
